// Package sotoon_kubernetes_engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package sotoon_kubernetes_engine

const (
	Bearer_TokenScopes = "Bearer_Token.Scopes"
)

// Defines values for ContainerNodeCRIConfigRuntime.
const (
	Containerd ContainerNodeCRIConfigRuntime = "containerd"
	Docker     ContainerNodeCRIConfigRuntime = "docker"
)

// Defines values for ContainerSotoonClusterApiVersion.
const (
	ContainerSotoonClusterApiVersionSkeSotoonIrv1alpha1 ContainerSotoonClusterApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for ContainerSotoonClusterKind.
const (
	ContainerSotoonClusterKindSotoonCluster ContainerSotoonClusterKind = "SotoonCluster"
)

// Defines values for ContainerSotoonClusterStatusPhase.
const (
	ContainerSotoonClusterStatusPhaseDeleting        ContainerSotoonClusterStatusPhase = "Deleting"
	ContainerSotoonClusterStatusPhaseFailed          ContainerSotoonClusterStatusPhase = "Failed"
	ContainerSotoonClusterStatusPhaseHighlyAvailable ContainerSotoonClusterStatusPhase = "HighlyAvailable"
	ContainerSotoonClusterStatusPhaseInitialized     ContainerSotoonClusterStatusPhase = "Initialized"
	ContainerSotoonClusterStatusPhaseProvisioned     ContainerSotoonClusterStatusPhase = "Provisioned"
	ContainerSotoonClusterStatusPhaseProvisioning    ContainerSotoonClusterStatusPhase = "Provisioning"
	ContainerSotoonClusterStatusPhaseReady           ContainerSotoonClusterStatusPhase = "Ready"
	ContainerSotoonClusterStatusPhaseUnknown         ContainerSotoonClusterStatusPhase = "Unknown"
	ContainerSotoonClusterStatusPhaseUpgrading       ContainerSotoonClusterStatusPhase = "Upgrading"
)

// Defines values for ContainerSotoonNodepoolApiVersion.
const (
	ContainerSotoonNodepoolApiVersionSkeSotoonIrv1alpha1 ContainerSotoonNodepoolApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for ContainerSotoonNodepoolKind.
const (
	ContainerSotoonNodepoolKindSotoonNodepool ContainerSotoonNodepoolKind = "SotoonNodepool"
)

// Defines values for ContainerSotoonNodepoolStatusPhase.
const (
	ContainerSotoonNodepoolStatusPhaseFailed       ContainerSotoonNodepoolStatusPhase = "Failed"
	ContainerSotoonNodepoolStatusPhaseProvisioning ContainerSotoonNodepoolStatusPhase = "Provisioning"
	ContainerSotoonNodepoolStatusPhaseRunning      ContainerSotoonNodepoolStatusPhase = "Running"
	ContainerSotoonNodepoolStatusPhaseScalingDown  ContainerSotoonNodepoolStatusPhase = "ScalingDown"
	ContainerSotoonNodepoolStatusPhaseScalingUp    ContainerSotoonNodepoolStatusPhase = "ScalingUp"
	ContainerSotoonNodepoolStatusPhaseUnknown      ContainerSotoonNodepoolStatusPhase = "Unknown"
)

// Defines values for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind.
const (
	PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKindSotoonCluster PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind = "SotoonCluster"
)

// Defines values for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion.
const (
	PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind.
const (
	PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKindSotoonCluster PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind = "SotoonCluster"
)

// Defines values for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion.
const (
	PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind.
const (
	PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKindSotoonCluster PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind = "SotoonCluster"
)

// Defines values for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind.
const (
	PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKindSotoonNodepool PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind = "SotoonNodepool"
)

// Defines values for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind.
const (
	PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKindSotoonNodepool PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind = "SotoonNodepool"
)

// Defines values for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion.
const (
	PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind.
const (
	PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKindSotoonNodepool PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind = "SotoonNodepool"
)

// Defines values for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind.
const (
	PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKindSotoonCluster PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind = "SotoonCluster"
)

// Defines values for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion.
const (
	PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind.
const (
	PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKindSotoonCluster PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind = "SotoonCluster"
)

// Defines values for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion.
const (
	PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind.
const (
	PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKindSotoonCluster PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind = "SotoonCluster"
)

// Defines values for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind.
const (
	PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKindSotoonNodepool PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind = "SotoonNodepool"
)

// Defines values for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind.
const (
	PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKindSotoonNodepool PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind = "SotoonNodepool"
)

// Defines values for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion.
const (
	PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind.
const (
	PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKindSotoonNodepool PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind = "SotoonNodepool"
)

// Defines values for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind.
const (
	PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKindSotoonCluster PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind = "SotoonCluster"
)

// Defines values for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion.
const (
	PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind.
const (
	PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKindSotoonCluster PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind = "SotoonCluster"
)

// Defines values for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion.
const (
	PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind.
const (
	PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKindSotoonCluster PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind = "SotoonCluster"
)

// Defines values for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind.
const (
	PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKindSotoonNodepool PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind = "SotoonNodepool"
)

// Defines values for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion.
const (
	PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind.
const (
	PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKindSotoonNodepool PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind = "SotoonNodepool"
)

// Defines values for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion.
const (
	PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersionSkeSotoonIrv1alpha1 PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind.
const (
	PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKindSotoonNodepool PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind = "SotoonNodepool"
)

// ContainerClusterInfrastructureSpec defines model for ContainerClusterInfrastructureSpec.
type ContainerClusterInfrastructureSpec struct {
	// VPC Virtual Private Cloud Network that the cluster is created in
	VPC string `json:"VPC"`

	// Subnet Engine sub-network that the cluster is created in
	Subnet  string              `json:"subnet"`
	Version ContainerSKEVersion `json:"version"`
}

// ContainerClusterNetwork defines model for ContainerClusterNetwork.
type ContainerClusterNetwork struct {
	Pods     *ContainerNetworkRanges `json:"pods,omitempty"`
	Services *ContainerNetworkRanges `json:"services,omitempty"`
}

// ContainerLocalObjectRef defines model for ContainerLocalObjectRef.
type ContainerLocalObjectRef struct {
	// Name Name of the referenced object
	Name *string `json:"name,omitempty"`
}

// ContainerNetworkRanges defines model for ContainerNetworkRanges.
type ContainerNetworkRanges struct {
	// CidrBlocks List of CIDR blocks
	CidrBlocks *[]string `json:"cidrBlocks"`
}

// ContainerNodeCRIConfig defines model for ContainerNodeCRIConfig.
type ContainerNodeCRIConfig struct {
	// Runtime Container runtime to use
	Runtime *ContainerNodeCRIConfigRuntime `json:"runtime,omitempty"`
}

// ContainerNodeCRIConfigRuntime Container runtime to use
type ContainerNodeCRIConfigRuntime string

// ContainerNodepoolPatchSpec defines model for ContainerNodepoolPatchSpec.
type ContainerNodepoolPatchSpec struct {
	// Replicas Number of worker nodes desired (0 or greater)
	Replicas *int `json:"replicas"`
}

// ContainerObjectMeta defines model for ContainerObjectMeta.
type ContainerObjectMeta struct {
	// Annotations Annotations store additional metadata about the resource
	Annotations *map[string]string `json:"annotations"`

	// CreationTimestamp Timestamp when the resource was initially created
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`

	// DeletionTimestamp Timestamp when the resource was marked for deletion
	DeletionTimestamp *string `json:"deletionTimestamp,omitempty"`

	// Labels Labels are key-value pairs attached to resources for organization and categorization
	Labels *map[string]string `json:"labels"`

	// Name User-provided name that uniquely identifies the resource within its workspace
	Name string `json:"name"`

	// ResourceVersion Internal version for optimistic concurrency control
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-generated unique identifier for the resource
	Uid *string `json:"uid,omitempty"`

	// Workspace Unique identifier of the workspace where the resource belongs
	Workspace *string `json:"workspace,omitempty"`
}

// ContainerSKEVersion defines model for ContainerSKEVersion.
type ContainerSKEVersion struct {
	// KubernetesVersion Kubernetes version
	KubernetesVersion *string `json:"kubernetesVersion,omitempty"`

	// PatchVersion SKE patch version
	PatchVersion *string `json:"patchVersion,omitempty"`
}

// ContainerSotoonCluster defines model for ContainerSotoonCluster.
type ContainerSotoonCluster struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion ContainerSotoonClusterApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     ContainerSotoonClusterKind    `json:"kind"`
	Metadata ContainerObjectMeta           `json:"metadata"`
	Spec     ContainerSotoonClusterSpec    `json:"spec"`
	Status   *ContainerSotoonClusterStatus `json:"status,omitempty"`
}

// ContainerSotoonClusterApiVersion Version identifier of the API schema
type ContainerSotoonClusterApiVersion string

// ContainerSotoonClusterKind The string value 'SotoonCluster' that identifies the schema
type ContainerSotoonClusterKind string

// ContainerSotoonClusterSpec defines model for ContainerSotoonClusterSpec.
type ContainerSotoonClusterSpec struct {
	ClusterNetwork *ContainerClusterNetwork           `json:"clusterNetwork,omitempty"`
	Infra          ContainerClusterInfrastructureSpec `json:"infra"`
}

// ContainerSotoonClusterStatus defines model for ContainerSotoonClusterStatus.
type ContainerSotoonClusterStatus struct {
	// Conditions Current conditions of the cluster
	Conditions           *[]V1Condition           `json:"conditions,omitempty"`
	KubeconfigSecretName *ContainerLocalObjectRef `json:"kubeconfigSecretName,omitempty"`

	// Phase Current phase of the cluster
	Phase *ContainerSotoonClusterStatusPhase `json:"phase,omitempty"`

	// Ready Indicates if the cluster is ready for use
	Ready *bool `json:"ready,omitempty"`

	// ReadyReplicas Number of ready replicas
	ReadyReplicas *int `json:"readyReplicas,omitempty"`

	// Replicas Total number of replicas
	Replicas *int `json:"replicas,omitempty"`

	// UnavailableReplicas Number of unavailable replicas
	UnavailableReplicas *int `json:"unavailableReplicas,omitempty"`

	// UpdatedReplicas Number of updated replicas
	UpdatedReplicas *int `json:"updatedReplicas,omitempty"`
}

// ContainerSotoonClusterStatusPhase Current phase of the cluster
type ContainerSotoonClusterStatusPhase string

// ContainerSotoonMachineTemplate defines model for ContainerSotoonMachineTemplate.
type ContainerSotoonMachineTemplate struct {
	// IamEnabled Enable IAM integration for nodes
	IamEnabled *bool `json:"iamEnabled,omitempty"`

	// InstanceType Instance type for worker nodes in Engine
	InstanceType string `json:"instanceType"`
}

// ContainerSotoonNodepool defines model for ContainerSotoonNodepool.
type ContainerSotoonNodepool struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion ContainerSotoonNodepoolApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     ContainerSotoonNodepoolKind    `json:"kind"`
	Metadata ContainerObjectMeta            `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec    `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus `json:"status,omitempty"`
}

// ContainerSotoonNodepoolApiVersion Version identifier of the API schema
type ContainerSotoonNodepoolApiVersion string

// ContainerSotoonNodepoolKind The string value 'SotoonNodepool' that identifies the schema
type ContainerSotoonNodepoolKind string

// ContainerSotoonNodepoolSpec defines model for ContainerSotoonNodepoolSpec.
type ContainerSotoonNodepoolSpec struct {
	// AllowedUnsafeSysctls List of allowed unsafe sysctls
	AllowedUnsafeSysctls *[]string `json:"allowedUnsafeSysctls,omitempty"`

	// ClusterName Name of the cluster this nodepool belongs to
	ClusterName string                  `json:"clusterName"`
	Cri         *ContainerNodeCRIConfig `json:"cri,omitempty"`

	// Labels Labels to apply to worker nodes
	Labels *map[string]string `json:"labels,omitempty"`

	// Replicas Number of worker nodes desired in the nodepool
	Replicas int                            `json:"replicas"`
	Template ContainerSotoonMachineTemplate `json:"template"`
	Version  *ContainerSKEVersion           `json:"version,omitempty"`
}

// ContainerSotoonNodepoolStatus defines model for ContainerSotoonNodepoolStatus.
type ContainerSotoonNodepoolStatus struct {
	// AvailableReplicas Number of replicas available for scheduling
	AvailableReplicas *int `json:"availableReplicas,omitempty"`

	// Conditions Current conditions of the nodepool
	Conditions *[]V1Condition `json:"conditions,omitempty"`

	// Phase Current phase of scaling operation
	Phase *ContainerSotoonNodepoolStatusPhase `json:"phase,omitempty"`

	// Ready Indicates if the nodepool is ready
	Ready *bool `json:"ready,omitempty"`

	// ReadyReplicas Number of replicas that are ready to serve traffic
	ReadyReplicas *int `json:"readyReplicas,omitempty"`

	// Replicas Current total number of replicas
	Replicas *int `json:"replicas,omitempty"`

	// UnavailableReplicas Number of replicas currently unavailable
	UnavailableReplicas *int `json:"unavailableReplicas,omitempty"`

	// UpdatedReplicas Number of replicas updated to the latest spec
	UpdatedReplicas *int `json:"updatedReplicas,omitempty"`
}

// ContainerSotoonNodepoolStatusPhase Current phase of scaling operation
type ContainerSotoonNodepoolStatusPhase string

// V1Condition defines model for V1Condition.
type V1Condition struct {
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`
	Message            *string `json:"message,omitempty"`
	ObservedGeneration *int    `json:"observedGeneration,omitempty"`
	Reason             *string `json:"reason,omitempty"`
	Status             *string `json:"status,omitempty"`
	Type               *string `json:"type,omitempty"`
}

// V1ListMeta defines model for V1ListMeta.
type V1ListMeta struct {
	Continue           *string `json:"continue,omitempty"`
	RemainingItemCount *int    `json:"remainingItemCount"`
	ResourceVersion    *string `json:"resourceVersion,omitempty"`
	SelfLink           *string `json:"selfLink,omitempty"`
}

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBody defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                      `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                               `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                            `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion string

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind string

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody defines parameters for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                 `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                          `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                                       `json:"status,omitempty"`
}

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion defines parameters for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion string

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind defines parameters for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind string

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody defines parameters for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                               `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                        `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                                     `json:"status,omitempty"`
}

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion defines parameters for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion string

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind defines parameters for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind string

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                       `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                               `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                            `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion string

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind string

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	Spec *ContainerNodepoolPatchSpec `json:"spec,omitempty"`
}

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                 `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                         `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                                      `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion string

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind defines parameters for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind string

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                        `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                                     `json:"status,omitempty"`
}

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion defines parameters for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion string

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind defines parameters for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind string

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBody defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                         `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                  `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                               `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion string

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind string

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody defines parameters for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                    `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                             `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                                          `json:"status,omitempty"`
}

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion defines parameters for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion string

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind defines parameters for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind string

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody defines parameters for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                  `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                           `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                                        `json:"status,omitempty"`
}

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion defines parameters for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion string

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind defines parameters for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind string

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                          `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                  `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                               `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion string

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind string

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	Spec *ContainerNodepoolPatchSpec `json:"spec,omitempty"`
}

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                    `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                            `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                                         `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion string

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind defines parameters for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind string

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                   `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                           `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                                        `json:"status,omitempty"`
}

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion defines parameters for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion string

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind defines parameters for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind string

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBody defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                          `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                   `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                                `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyApiVersion string

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclusters.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBodyKind string

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody defines parameters for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                     `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                              `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                                           `json:"status,omitempty"`
}

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion defines parameters for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion string

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind defines parameters for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind string

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody defines parameters for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind     PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                   `json:"metadata"`
	Spec     ContainerSotoonClusterSpec                                                            `json:"spec"`
	Status   *ContainerSotoonClusterStatus                                                         `json:"status,omitempty"`
}

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion defines parameters for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyApiVersion string

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind defines parameters for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBodyKind string

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                           `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                   `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                                `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyApiVersion string

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepools.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBodyKind string

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	Spec *ContainerNodepoolPatchSpec `json:"spec,omitempty"`
}

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                     `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                             `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                                          `json:"status,omitempty"`
}

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion string

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind defines parameters for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind string

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody defines parameters for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind     PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind `json:"kind"`
	Metadata ContainerObjectMeta                                                                    `json:"metadata"`
	Spec     ContainerSotoonNodepoolSpec                                                            `json:"spec"`
	Status   *ContainerSotoonNodepoolStatus                                                         `json:"status,omitempty"`
}

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion defines parameters for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyApiVersion string

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind defines parameters for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBodyKind string

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody defines body for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclusters for application/json ContentType.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONBody

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody defines body for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepools for application/json ContentType.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody defines body for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclusters for application/json ContentType.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONBody

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody defines body for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepools for application/json ContentType.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody defines body for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclusters for application/json ContentType.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONBody

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONBody

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody defines body for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepools for application/json ContentType.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONBody

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONBody
