// Package sotoon_kubernetes_engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package sotoon_kubernetes_engine

import (
	"time"
)

const (
	Bearer_TokenScopes = "Bearer_Token.Scopes"
)

// Defines values for ContainerNodeCRIConfigRuntime.
const (
	Containerd ContainerNodeCRIConfigRuntime = "containerd"
	Docker     ContainerNodeCRIConfigRuntime = "docker"
)

// Defines values for ContainerSotoonClusterApiVersion.
const (
	ContainerSotoonClusterApiVersionSkeSotoonIrv1alpha1 ContainerSotoonClusterApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for ContainerSotoonClusterKind.
const (
	SotoonCluster ContainerSotoonClusterKind = "SotoonCluster"
)

// Defines values for ContainerSotoonClusterListKind.
const (
	SotoonClusterList ContainerSotoonClusterListKind = "SotoonClusterList"
)

// Defines values for ContainerSotoonClusterStatusPhase.
const (
	ContainerSotoonClusterStatusPhaseDeleting        ContainerSotoonClusterStatusPhase = "Deleting"
	ContainerSotoonClusterStatusPhaseFailed          ContainerSotoonClusterStatusPhase = "Failed"
	ContainerSotoonClusterStatusPhaseHighlyAvailable ContainerSotoonClusterStatusPhase = "HighlyAvailable"
	ContainerSotoonClusterStatusPhaseInitialized     ContainerSotoonClusterStatusPhase = "Initialized"
	ContainerSotoonClusterStatusPhaseProvisioned     ContainerSotoonClusterStatusPhase = "Provisioned"
	ContainerSotoonClusterStatusPhaseProvisioning    ContainerSotoonClusterStatusPhase = "Provisioning"
	ContainerSotoonClusterStatusPhaseReady           ContainerSotoonClusterStatusPhase = "Ready"
	ContainerSotoonClusterStatusPhaseUnknown         ContainerSotoonClusterStatusPhase = "Unknown"
	ContainerSotoonClusterStatusPhaseUpgrading       ContainerSotoonClusterStatusPhase = "Upgrading"
)

// Defines values for ContainerSotoonNodepoolApiVersion.
const (
	ContainerSotoonNodepoolApiVersionSkeSotoonIrv1alpha1 ContainerSotoonNodepoolApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for ContainerSotoonNodepoolKind.
const (
	SotoonNodepool ContainerSotoonNodepoolKind = "SotoonNodepool"
)

// Defines values for ContainerSotoonNodepoolListKind.
const (
	SotoonNodepoolList ContainerSotoonNodepoolListKind = "SotoonNodepoolList"
)

// Defines values for ContainerSotoonNodepoolStatusPhase.
const (
	ContainerSotoonNodepoolStatusPhaseFailed       ContainerSotoonNodepoolStatusPhase = "Failed"
	ContainerSotoonNodepoolStatusPhaseProvisioning ContainerSotoonNodepoolStatusPhase = "Provisioning"
	ContainerSotoonNodepoolStatusPhaseRunning      ContainerSotoonNodepoolStatusPhase = "Running"
	ContainerSotoonNodepoolStatusPhaseScalingDown  ContainerSotoonNodepoolStatusPhase = "ScalingDown"
	ContainerSotoonNodepoolStatusPhaseScalingUp    ContainerSotoonNodepoolStatusPhase = "ScalingUp"
	ContainerSotoonNodepoolStatusPhaseUnknown      ContainerSotoonNodepoolStatusPhase = "Unknown"
)

// Defines values for ContainerStatusApiVersion.
const (
	SkeSotoonIrv1alpha1 ContainerStatusApiVersion = "ske.sotoon.ir/v1alpha1"
)

// Defines values for ContainerStatusKind.
const (
	Status ContainerStatusKind = "Status"
)

// Defines values for ContainerStatusStatus.
const (
	Failure ContainerStatusStatus = "Failure"
	Success ContainerStatusStatus = "Success"
)

// ContainerClusterInfrastructureSpec Infrastructure configuration for the cluster
type ContainerClusterInfrastructureSpec struct {
	// VPC Virtual Private Cloud Network that the cluster is created in
	VPC string `json:"VPC"`

	// Subnet Engine sub-network that the cluster is created in
	Subnet string `json:"subnet"`

	// Version Control-plane version configuration
	Version ContainerSKEVersion `json:"version"`
}

// ContainerClusterNetwork Network configuration for the cluster
type ContainerClusterNetwork struct {
	// Pods Network ranges from which Pod networks are allocated
	Pods *ContainerNetworkRanges `json:"pods"`

	// Services Network ranges from which Pod networks are allocated
	Services *ContainerNetworkRanges `json:"services"`
}

// ContainerLocalObjectRef Reference to the kubeconfig secret
type ContainerLocalObjectRef struct {
	// Name Name of the referenced object
	Name string `json:"name"`
}

// ContainerNetworkRanges Network ranges from which Pod networks are allocated
type ContainerNetworkRanges struct {
	// CidrBlocks List of CIDR blocks
	CidrBlocks []string `json:"cidrBlocks"`
}

// ContainerNodeCRIConfig Container runtime configuration
type ContainerNodeCRIConfig struct {
	// Runtime Container runtime to use
	Runtime ContainerNodeCRIConfigRuntime `json:"runtime"`
}

// ContainerNodeCRIConfigRuntime Container runtime to use
type ContainerNodeCRIConfigRuntime string

// ContainerNodepoolPatchRequest defines model for containerNodepoolPatchRequest.
type ContainerNodepoolPatchRequest struct {
	// Spec Specification for nodepool updates
	Spec ContainerNodepoolPatchSpec `json:"spec"`
}

// ContainerNodepoolPatchSpec Specification for nodepool updates
type ContainerNodepoolPatchSpec struct {
	// Replicas Number of worker nodes desired (0 or greater)
	Replicas *int32 `json:"replicas"`
}

// ContainerObjectMeta Standard resource metadata fields
type ContainerObjectMeta struct {
	// Annotations Annotations store additional metadata about the resource
	Annotations       map[string]string `json:"annotations"`
	CreationTimestamp V1Time            `json:"creationTimestamp"`
	DeletionTimestamp V1Time            `json:"deletionTimestamp"`

	// Labels Labels are key-value pairs attached to resources for organization and categorization
	Labels map[string]string `json:"labels"`

	// Name User-provided name that uniquely identifies the resource within its workspace
	Name string `json:"name"`

	// ResourceVersion Internal version for optimistic concurrency control
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// Uid System-generated unique identifier for the resource
	Uid string `json:"uid"`

	// Workspace Unique identifier of the workspace where the resource belongs
	Workspace string `json:"workspace"`
}

// ContainerSKEVersion Control-plane version configuration
type ContainerSKEVersion struct {
	// KubernetesVersion Kubernetes version
	KubernetesVersion string `json:"kubernetesVersion"`

	// PatchVersion SKE patch version
	PatchVersion string `json:"patchVersion"`
}

// ContainerSotoonCluster defines model for containerSotoonCluster.
type ContainerSotoonCluster struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion ContainerSotoonClusterApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonCluster' that identifies the schema
	Kind ContainerSotoonClusterKind `json:"kind"`

	// Metadata Standard resource metadata fields
	Metadata ContainerObjectMeta `json:"metadata"`

	// Spec Desired configuration for the Kubernetes cluster
	Spec ContainerSotoonClusterSpec `json:"spec"`

	// Status Current observed state of the cluster
	Status ContainerSotoonClusterStatus `json:"status"`
}

// ContainerSotoonClusterApiVersion Version identifier of the API schema
type ContainerSotoonClusterApiVersion string

// ContainerSotoonClusterKind The string value 'SotoonCluster' that identifies the schema
type ContainerSotoonClusterKind string

// ContainerSotoonClusterList defines model for containerSotoonClusterList.
type ContainerSotoonClusterList struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion string `json:"apiVersion"`

	// Items Collection of SotoonCluster resources
	Items []ContainerSotoonCluster `json:"items"`

	// Kind The string value 'SotoonClusterList'
	Kind ContainerSotoonClusterListKind `json:"kind"`

	// Metadata Standard metadata fields
	Metadata V1ListMeta `json:"metadata"`
}

// ContainerSotoonClusterListKind The string value 'SotoonClusterList'
type ContainerSotoonClusterListKind string

// ContainerSotoonClusterSpec Desired configuration for the Kubernetes cluster
type ContainerSotoonClusterSpec struct {
	// ClusterNetwork Network configuration for the cluster
	ClusterNetwork *ContainerClusterNetwork `json:"clusterNetwork"`

	// Infra Infrastructure configuration for the cluster
	Infra ContainerClusterInfrastructureSpec `json:"infra"`
}

// ContainerSotoonClusterStatus Current observed state of the cluster
type ContainerSotoonClusterStatus struct {
	// Conditions Current conditions of the cluster
	Conditions *[]V1Condition `json:"conditions,omitempty"`

	// KubeconfigSecretName Reference to the kubeconfig secret
	KubeconfigSecretName *ContainerLocalObjectRef `json:"kubeconfigSecretName"`

	// Phase Current phase of the cluster
	Phase ContainerSotoonClusterStatusPhase `json:"phase"`

	// Ready Indicates if the cluster is ready for use
	Ready bool `json:"ready"`

	// ReadyReplicas Number of ready replicas
	ReadyReplicas int32 `json:"readyReplicas"`

	// Replicas Total number of replicas
	Replicas int32 `json:"replicas"`

	// UnavailableReplicas Number of unavailable replicas
	UnavailableReplicas int32 `json:"unavailableReplicas"`

	// UpdatedReplicas Number of updated replicas
	UpdatedReplicas int32 `json:"updatedReplicas"`
}

// ContainerSotoonClusterStatusPhase Current phase of the cluster
type ContainerSotoonClusterStatusPhase string

// ContainerSotoonMachineTemplate Template configuration for worker nodes
type ContainerSotoonMachineTemplate struct {
	// IamEnabled Enable IAM integration for nodes
	IamEnabled bool `json:"iamEnabled"`

	// InstanceType Instance type for worker nodes in Engine
	InstanceType string `json:"instanceType"`
}

// ContainerSotoonNodepool defines model for containerSotoonNodepool.
type ContainerSotoonNodepool struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion ContainerSotoonNodepoolApiVersion `json:"apiVersion"`

	// Kind The string value 'SotoonNodepool' that identifies the schema
	Kind ContainerSotoonNodepoolKind `json:"kind"`

	// Metadata Standard resource metadata fields
	Metadata ContainerObjectMeta `json:"metadata"`

	// Spec Desired configuration for the nodepool
	Spec ContainerSotoonNodepoolSpec `json:"spec"`

	// Status Current observed state of the nodepool
	Status ContainerSotoonNodepoolStatus `json:"status"`
}

// ContainerSotoonNodepoolApiVersion Version identifier of the API schema
type ContainerSotoonNodepoolApiVersion string

// ContainerSotoonNodepoolKind The string value 'SotoonNodepool' that identifies the schema
type ContainerSotoonNodepoolKind string

// ContainerSotoonNodepoolList defines model for containerSotoonNodepoolList.
type ContainerSotoonNodepoolList struct {
	// ApiVersion Version identifier of the API schema
	ApiVersion string `json:"apiVersion"`

	// Items Collection of SotoonNodepool resources
	Items []ContainerSotoonNodepool `json:"items"`

	// Kind The string value 'SotoonNodepoolList'
	Kind ContainerSotoonNodepoolListKind `json:"kind"`

	// Metadata Standard metadata fields
	Metadata V1ListMeta `json:"metadata"`
}

// ContainerSotoonNodepoolListKind The string value 'SotoonNodepoolList'
type ContainerSotoonNodepoolListKind string

// ContainerSotoonNodepoolSpec Desired configuration for the nodepool
type ContainerSotoonNodepoolSpec struct {
	// AllowedUnsafeSysctls List of allowed unsafe sysctls
	AllowedUnsafeSysctls *[]string `json:"allowedUnsafeSysctls,omitempty"`

	// ClusterName Name of the cluster this nodepool belongs to
	ClusterName string `json:"clusterName"`

	// Cri Container runtime configuration
	Cri *ContainerNodeCRIConfig `json:"cri"`

	// Labels Labels to apply to worker nodes
	Labels *map[string]string `json:"labels,omitempty"`

	// Replicas Number of worker nodes desired in the nodepool
	Replicas int32 `json:"replicas"`

	// Template Template configuration for worker nodes
	Template ContainerSotoonMachineTemplate `json:"template"`

	// Version Control-plane version configuration
	Version ContainerSKEVersion `json:"version"`
}

// ContainerSotoonNodepoolStatus Current observed state of the nodepool
type ContainerSotoonNodepoolStatus struct {
	// AvailableReplicas Number of replicas available for scheduling
	AvailableReplicas int32 `json:"availableReplicas"`

	// Conditions Current conditions of the nodepool
	Conditions *[]V1Condition `json:"conditions,omitempty"`

	// Phase Current phase of scaling operation
	Phase ContainerSotoonNodepoolStatusPhase `json:"phase"`

	// Ready Indicates if the nodepool is ready
	Ready bool `json:"ready"`

	// ReadyReplicas Number of replicas that are ready to serve traffic
	ReadyReplicas int32 `json:"readyReplicas"`

	// Replicas Current total number of replicas
	Replicas int32 `json:"replicas"`

	// UnavailableReplicas Number of replicas currently unavailable
	UnavailableReplicas int32 `json:"unavailableReplicas"`

	// UpdatedReplicas Number of replicas updated to the latest spec
	UpdatedReplicas int32 `json:"updatedReplicas"`
}

// ContainerSotoonNodepoolStatusPhase Current phase of scaling operation
type ContainerSotoonNodepoolStatusPhase string

// ContainerStatus defines model for containerStatus.
type ContainerStatus struct {
	// ApiVersion Version of the Status kind
	ApiVersion ContainerStatusApiVersion `json:"apiVersion"`

	// Code HTTP status code corresponding to this status
	Code int32 `json:"code"`

	// Kind Value is always 'Status'
	Kind ContainerStatusKind `json:"kind"`

	// Message Human-readable description of the status
	Message *string `json:"message,omitempty"`

	// Metadata Standard metadata fields
	Metadata *V1ListMeta `json:"metadata,omitempty"`

	// Reason Machine-readable description of the cause
	Reason *string `json:"reason,omitempty"`

	// Status Status of the operation
	Status ContainerStatusStatus `json:"status"`
}

// ContainerStatusApiVersion Version of the Status kind
type ContainerStatusApiVersion string

// ContainerStatusKind Value is always 'Status'
type ContainerStatusKind string

// ContainerStatusStatus Status of the operation
type ContainerStatusStatus string

// V1Condition defines model for v1Condition.
type V1Condition struct {
	LastTransitionTime V1Time `json:"lastTransitionTime"`
	Message            string `json:"message"`
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	Reason             string `json:"reason"`
	Status             string `json:"status"`
	Type               string `json:"type"`
}

// V1ListMeta Standard metadata fields
type V1ListMeta struct {
	Continue           *string `json:"continue,omitempty"`
	RemainingItemCount *int64  `json:"remainingItemCount"`
	ResourceVersion    *string `json:"resourceVersion,omitempty"`
	SelfLink           *string `json:"selfLink,omitempty"`
}

// V1Time defines model for v1Time.
type V1Time = time.Time

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody defines body for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclusters for application/json ContentType.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody = ContainerSotoonCluster

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody = ContainerSotoonCluster

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody = ContainerSotoonCluster

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody defines body for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepools for application/json ContentType.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody = ContainerSotoonNodepool

// PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerNodepoolPatchRequest

// PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PostSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerSotoonNodepool

// PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1FreeWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerSotoonNodepool

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody defines body for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclusters for application/json ContentType.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody = ContainerSotoonCluster

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody = ContainerSotoonCluster

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody = ContainerSotoonCluster

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody defines body for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepools for application/json ContentType.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody = ContainerSotoonNodepool

// PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerNodepoolPatchRequest

// PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PostSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerSotoonNodepool

// PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1PremiumWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerSotoonNodepool

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody defines body for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclusters for application/json ContentType.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersJSONRequestBody = ContainerSotoonCluster

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody = ContainerSotoonCluster

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonclustersResourceIdJSONRequestBody = ContainerSotoonCluster

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody defines body for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepools for application/json ContentType.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsJSONRequestBody = ContainerSotoonNodepool

// PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PatchSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerNodepoolPatchRequest

// PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PostSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerSotoonNodepool

// PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody defines body for PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceId for application/json ContentType.
type PutSkeV2alpha1Thr1StandardWorkspacesWorkspaceUUIDSotoonnodepoolsResourceIdJSONRequestBody = ContainerSotoonNodepool
